/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 *
 * @author ACER
 */
public class education extends javax.swing.JFrame {
    String filePDF;

    /**
     * Creates new form education
     */
    public education() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        scrollPanel = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        cbSelect = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnSelect = new javax.swing.JButton();
        edukasi = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        skedul = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bng = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1152, 816));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1152, 816));

        jPanel12.setMinimumSize(new java.awt.Dimension(1170, 816));
        jPanel12.setPreferredSize(new java.awt.Dimension(1152, 816));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel12.add(scrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 570, 730));

        jLabel2.setText("Pilih File edukasi Pertanian :");
        jPanel12.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        cbSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Periode Musim Tanam", "Budidaya Padi BPPP KemenPer 2016", "Budidaya Padi BPPP KemenPer 2013" }));
        cbSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectActionPerformed(evt);
            }
        });
        jPanel12.add(cbSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 250, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText(".pdf");
        jPanel12.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, 30));

        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        jPanel12.add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        edukasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edukasiMouseClicked(evt);
            }
        });
        jPanel12.add(edukasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 30, 40));

        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        jPanel12.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 30, 40));

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jPanel12.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 30, 40));

        skedul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                skedulMouseClicked(evt);
            }
        });
        jPanel12.add(skedul, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 30, 40));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 750, 40, 60));

        bng.setForeground(new java.awt.Color(255, 255, 255));
        bng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/bgn4.png"))); // NOI18N
        jPanel12.add(bng, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edukasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edukasiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_edukasiMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_homeMouseClicked

    private void cbSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSelectActionPerformed

    private void skedulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skedulMouseClicked
        // TODO add your handling code here:
        skedul s = new skedul();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_skedulMouseClicked

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        filePDF = (String) cbSelect.getSelectedItem();
        
        if(null!=filePDF) switch(filePDF){
            case "Periode Musim Tanam":
                openpdf("src//books//periodeFarm.pdf");
                break;
            case "Budidaya Padi BPPP KemenPer 2016":
                openpdf("src//books//BudidayaPadi.pdf");
                break;
            case "Budidaya Padi BPPP KemenPer 2013":
                openpdf("src//books//03_BudiDayaPadi.pdf");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(education.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(education.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(education.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(education.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new education().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel bng;
    private javax.swing.JButton btnSelect;
    private javax.swing.JComboBox<String> cbSelect;
    private javax.swing.JLabel edukasi;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JLabel skedul;
    // End of variables declaration//GEN-END:variables


    private void openpdf(String file) {
        try {
            SwingController control = new SwingController();
            SwingViewBuilder factry = new SwingViewBuilder(control);
            JPanel viewerCompntpn1 = factry.buildViewerPanel();
            ComponentKeyBinding.install(control,viewerCompntpn1);
            control.getDocumentViewController().setAnnotationCallback(new org.icepdf.ri.common.MyAnnotationCallback(control.getDocumentViewController()));
            control.openDocument(file);
            scrollPanel.setViewportView(viewerCompntpn1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot Load .PDF");
        }
    }
}
